project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!assets/"

website:
  title: "Startai Ecosystem"
  favicon: "assets/img/startai_logo_only.png"

  page-navigation: true

  navbar:
    title: false
    search: true
    pinned: true
    logo: "assets/img/startai_logo_text.png"
    logo-href: https://khulnasoft.com
    left:
      - text: "Github"
        href: https://github.com/khulnasoft/startai
      - text: "Docs"
        href: https://khulnasoft.com/docs/startai
      - text: "Discord"
        href: https://discord.com/invite/sXyFF8tDtm

  sidebar:
    style: "floating"
    border: true
    collapse-level: 1
    contents:
      - text: "Home"
        href: index.qmd      
      - section: "Docs"
        contents:
          - text: "Startai"
            href: https://khulnasoft.com/docs/startai
          - text: "Startai Mech"
            href: https://khulnasoft.com/docs/mech
          - text: "Startai Vision"
            href: https://khulnasoft.com/docs/vision
          - text: "Startai Robot"
            href: https://khulnasoft.com/docs/robot
          - text: "Startai Gym"
            href: https://khulnasoft.com/docs/gym
          - text: "Startai Memory"
            href: https://khulnasoft.com/docs/memory
          - text: "Startai Builder"
            href: https://khulnasoft.com/docs/builder
          - text: "Startai Models"
            href: https://khulnasoft.com/docs/models
          - text: "Startai Ecosystem"
            href: https://khulnasoft.com/docs/ecosystem
          

format:
  html:
    toc: true
    include-after-body:
      - file: assets/generate_badges.html
    theme: assets/css/custom.scss
    page-layout: full
    code-overflow: scroll
    jupyter: python3
    monobackgroundcolor: "#ffffff"
    execute:
      echo: true
      output: true
      eval: true
